version: "3"
services:
  api:
    platform: linux/amd64
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=ee1260494d8f102408ce1a5632f18618f682308f5eb11bb8dd509d68ac3f0781
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
